### ISSUE TITLE
Funções com problemas

### ISSUE THREAD

**Issue by Mau-Me** [tiagolpadua/las-api#56]
### As seguintes funções podem estar apresentando problemas:

- extrairPrimeiroNome
- calculaImposto
- truncar

**Comment by tiagolpadua** [comment]
Hum, vc poderia detalhar um pouco mais qual seria o problema identificado?

**Comment by sglauber** [comment]
Tiago, que o problema na `calculaImposto()` é descrito a seguir:
Como o projeto está sendo implementado de forma incremental (imagino, que estaremos utilizando ele para os próximos desafios ) deveríamos utilizar as funções já criadas anteriormente para evitar repetição, como por exemplo, sendo possível utilizar `calculaImposto( )` para obter o imposto de um valor com base na categoria, porém na implementação utilizada em funcoes.js esse cálculo não é realizado nos sendo retornado (0 ou 1), dessa forma a utilização da função se torna inviável a não ser que possamos alterar o código de funcoes.js.

Obs.:¹ Nos foi dito que deveríamos alterar apenas o código de arrays.js.
