### ISSUE TITLE
Teste da função obterDescontoTotal

### ISSUE THREAD

**Issue by Mau-Me** [tiagolpadua/las-api#57]
O teste da função obterDescontoTotal deveria verificar se houve um acréscimo de 10% quando utilizado um cupom válido, mas na verdade está verificando o acrésimo de mais 10 ao valor do desconto.

Segue uma imagem de exemplo:

![issue](https://user-images.githubusercontent.com/20570844/150995738-a0bb050d-dcf9-48b3-ab18-81d45131dc45.png)

**Comment by Mau-Me** [comment]
E ao escrever a função para passar no teste o cálculo da função calcularTotalDaCompraComDescontos fica incorreto, pois ele espera que seja feito com os 10%.

**Comment by tiagolpadua** [comment]
Hum, mas vc considerou que há o desconto da categoria + o desconto do cupom? 
O resultado esperado é "descontoDaCategoria + descontoDoCupom", veja se vc concorda

**Comment by alexandreaquiles** [comment]
Opa, @Mau-Me. O resultado aqui é um valor de 0 a 100.

Um _acréscimo de 10%_ aqui, é somar 10% nos 30%, o que daria **40%**.

**Comment by Mau-Me** [comment]
Entendi sim!
Foi erro de compreensão mesmo 😆

Obrigado pelo retorno

**Comment by tiagolpadua** [comment]
Legal @Mau-Me , não deixe de comentar quando achar q algo pode estar errado, até pq pode realmente ter alguma incorreção que passe batido. ;-)
